insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Allsun', 'McNiff', 'Philippines');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Nicolina', 'Serot', 'South Africa');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Wanda', 'Arnfield', 'Japan');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Bird', 'Atwill', 'Portugal');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Celestia', 'Carde', 'China');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Cassandra', 'Smeed', 'Indonesia');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Agretha', 'Taberner', 'Thailand');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Kane', 'Bondar', 'China');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Gannie', 'Ellick', 'Ireland');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Desmund', 'Ewen', 'Syria');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Rosie', 'Ollet', 'Japan');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Raddie', 'Djokic', 'Czech Republic');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Aluino', 'Dymond', 'Philippines');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Kaiser', 'Haney`', 'China');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Cosetta', 'Bess', 'Ukraine');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Mauricio', 'Fridd', 'Russia');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Bert', 'Meanwell', 'China');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Leelah', 'Rosoman', 'Sweden');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Brody', 'Messingham', 'France');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Sharity', 'O''Heaney', 'Russia');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Alfi', 'Filipovic', 'Italy');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Ivar', 'Naulty', 'France');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Hannis', 'Fayer', 'China');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Ingaberg', 'Tookey', 'Mexico');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Gabbie', 'Greenstreet', 'Japan');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Keane', 'Emslie', 'China');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Marietta', 'Oene', 'France');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Eddy', 'Jacobsson', 'United States');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Malorie', 'Wedmore.', 'Madagascar');
insert into Client (id, username, last_name, country) values (NEXTVAL('hibernate_sequence'), 'Margo', 'Moakson', 'Greece');
